### ISSUE TITLE
[bug] hide() does not appear to be working anymore

### ISSUE THREAD

**Issue by MartenPostma** [Corderius-College-Amersfoort/play#16]
### What happened?

A bug happened!

import play

tekst = play.new_text(
    words='Je hebt gewonnen!',
    x=0,
    y=0,
)
tekst.hide()

play.start_program()

the text does not hide

### Version

latest

**Comment by koen1711** [comment]
This is due to us not caring about is_hidden and instead calling .update() always, we'll fix by introducing a way to "LOCK" updates on a sprite, which prevents the .update() method from being called, this will also pave a way for future features, for example .lock() stops all graphical updates on a sprite, allowing you to run for example a physics simulation and only after it's finished update the screen.
